spring:
  profiles:
    active: dev
  application:
    name: iLog
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

servlet:
  multipart:
    location: C:/uploadPath

childProfileImgWindowsPath: C:/ilog/childProfileImgs
childProfileImgMacPath: /Users/hojooneum/Downloads/scit/team-project/backend/childProfileImgs
childHealthCheckImgWindowsPath: C:/ilog/childHealthCheckImgs
childHealthCheckImgMacPath: /Users/hojooneum/Downloads/scit/team-project/backend/childHealthCheckImgs

