spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/ilog
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ilog
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        sql_format: true
        highlight_sql: true


