server:
  port: 9900
spring:
  profiles:
    active: dev
  application:
    name: iLog
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: bldolphin96@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

childProfileImgWindowsPath: file://C:/ilog/childProfileImgs
childProfileImgMacPath: /Users/hojooneum/Downloads/scit/team-project/backend/childProfileImgs
childHealthCheckImgWindowsPath: file://C:/ilog/childHealthCheckImgs
childHealthCheckImgMacPath: /Users/hojooneum/Downloads/scit/team-project/backend/childHealthCheckImgs
childAnalysisFileImgWindowsPath: file://C:/ilog/childAnalysisFiles
childAnalysisFileMacPath: /Users/hojooneum/Downloads/scit/team-project/backend/childAnalysisFiles

#  Windows 경로를 사용할 때는 "file:///" (슬래시 3개)를 사용
#  Unix/Linux 시스템에서는 "file://" (슬래시 2개)를 사용
#  경로 구분자는 항상 forward slash(/)를 사용 (Windows의 백슬래시가 아님)
#
#  만약 "file://" 접두어를 붙이지 않으면, Spring Boot는 해당 경로를 클래스패스 내의 리소스로 인식하려고 시도하기 때문에 외부 파일 시스템의 리소스를 찾지 못할 수 있습니다.

