server:
  port: 9900
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ilog?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        show_sql: true
        sql_format: true
        highlight_sql: true


